"""add resolution embeddings and review queue tables

Revision ID: 686c04b3f09c
Revises: 71735db5186b
Create Date: 2026-08-19 19:15:51.264758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '686c04b3f09c'
down_revision: Union[str, Sequence[str], None] = '71735db5186b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('source_image_storage_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_embeddings_case_id'), 'resolution_embeddings', ['case_id'], unique=False)
    op.create_index('ix_resolution_embeddings_embedding_hnsw', 'resolution_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_resolution_embeddings_event_id'), 'resolution_embeddings', ['event_id'], unique=False)
    op.create_index(op.f('ix_resolution_embeddings_target_entity_id'), 'resolution_embeddings', ['target_entity_id'], unique=False)
    op.create_table('review_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('candidate_target_entity_id', sa.String(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('top_candidates', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['embedding_id'], ['resolution_embeddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_items_case_id'), 'review_queue_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_queue_items_embedding_id'), 'review_queue_items', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_review_queue_items_event_id'), 'review_queue_items', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_items_event_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_embedding_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_case_id'), table_name='review_queue_items')
    op.drop_table('review_queue_items')
    op.drop_index(op.f('ix_resolution_embeddings_target_entity_id'), table_name='resolution_embeddings')
    op.drop_index(op.f('ix_resolution_embeddings_event_id'), table_name='resolution_embeddings')
    op.drop_index('ix_resolution_embeddings_embedding_hnsw', table_name='resolution_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_resolution_embeddings_case_id'), table_name='resolution_embeddings')
    op.drop_table('resolution_embeddings')
    # ### end Alembic commands ###
