"""add video processing tables

Revision ID: 71735db5186b
Revises: 
Create Date: 2026-08-14 15:08:28.967384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '71735db5186b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Owned by this migration (not the Docker image) so schema setup is
    # reproducible from `alembic upgrade head` alone in any environment.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('video_storage_key', sa.String(), nullable=True),
    sa.Column('interval_seconds', sa.Float(), nullable=False),
    sa.Column('embed_interval_seconds', sa.Float(), nullable=False),
    sa.Column('min_quality', sa.Float(), nullable=False),
    sa.Column('min_blur', sa.Float(), nullable=False),
    sa.Column('full_detection_every_frame', sa.Boolean(), nullable=False),
    sa.Column('iou_threshold', sa.Float(), nullable=False),
    sa.Column('cluster_eps', sa.Float(), nullable=False),
    sa.Column('cluster_min_samples', sa.Integer(), nullable=False),
    sa.Column('expected_frames', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_job_id'), 'videos', ['job_id'], unique=False)
    op.create_table('person_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('track_local_id', sa.Integer(), nullable=False),
    sa.Column('best_face_detection_id', sa.UUID(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=False),
    sa.Column('representative_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # best_face_detection_id -> face_detections.id is added below via
    # op.create_foreign_key, once face_detections exists - these two tables
    # reference each other, so the constraint can't be inline here.
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'track_local_id', name='uq_person_track_video_local_id')
    )
    op.create_index('ix_person_tracks_representative_embedding_hnsw', 'person_tracks', ['representative_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'representative_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_person_tracks_video_id'), 'person_tracks', ['video_id'], unique=False)
    op.create_table('face_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('person_track_id', sa.UUID(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('is_embedding', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('estimated_age', sa.Integer(), nullable=True),
    sa.Column('estimated_gender', sa.String(), nullable=True),
    sa.Column('crop_storage_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('bbox IS NULL OR array_length(bbox, 1) = 4', name='ck_face_detection_bbox_len'),
    sa.ForeignKeyConstraint(['person_track_id'], ['person_tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_detections_embedding_hnsw', 'face_detections', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_face_detections_person_track_id'), 'face_detections', ['person_track_id'], unique=False)
    op.create_index(op.f('ix_face_detections_video_id'), 'face_detections', ['video_id'], unique=False)
    op.create_foreign_key(
        'fk_person_tracks_best_face_detection_id',
        'person_tracks', 'face_detections',
        ['best_face_detection_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_person_tracks_best_face_detection_id', 'person_tracks', type_='foreignkey')
    op.drop_index(op.f('ix_face_detections_video_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_person_track_id'), table_name='face_detections')
    op.drop_index('ix_face_detections_embedding_hnsw', table_name='face_detections', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('face_detections')
    op.drop_index(op.f('ix_person_tracks_video_id'), table_name='person_tracks')
    op.drop_index('ix_person_tracks_representative_embedding_hnsw', table_name='person_tracks', postgresql_using='hnsw', postgresql_ops={'representative_embedding': 'vector_cosine_ops'})
    op.drop_table('person_tracks')
    op.drop_index(op.f('ix_videos_job_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
