"""add identity face templates and review queue candidate kind

Revision ID: c1854a02a12c
Revises: 686c04b3f09c
Create Date: 2026-08-19 22:18:52.492560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c1854a02a12c'
down_revision: Union[str, Sequence[str], None] = '686c04b3f09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_face_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('source_image_storage_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_identity_face_templates_embedding_hnsw', 'identity_face_templates', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_identity_face_templates_identity_id'), 'identity_face_templates', ['identity_id'], unique=False)
    # server_default backfills existing rows (all pre-existing review_queue_items
    # were "cluster" candidates - candidate_kind didn't exist before this
    # migration); dropped immediately after since app code always sets
    # this explicitly going forward.
    op.add_column(
        'review_queue_items',
        sa.Column('candidate_kind', sa.String(), nullable=False, server_default='cluster'),
    )
    op.alter_column('review_queue_items', 'candidate_kind', server_default=None)
    op.add_column('review_queue_items', sa.Column('candidate_identity_id', sa.String(), nullable=True))
    op.alter_column('review_queue_items', 'candidate_target_entity_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_queue_items', 'candidate_target_entity_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('review_queue_items', 'candidate_identity_id')
    op.drop_column('review_queue_items', 'candidate_kind')
    op.drop_index(op.f('ix_identity_face_templates_identity_id'), table_name='identity_face_templates')
    op.drop_index('ix_identity_face_templates_embedding_hnsw', table_name='identity_face_templates', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('identity_face_templates')
    # ### end Alembic commands ###
