// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Comparison struct {
	ID              int64          `db:"id" json:"id"`
	EvidenceA       string         `db:"evidence_a" json:"evidence_a"`
	EvidenceB       string         `db:"evidence_b" json:"evidence_b"`
	CaseType        string         `db:"case_type" json:"case_type"`
	ComparisonType  string         `db:"comparison_type" json:"comparison_type"`
	ResponsibleUser sql.NullString `db:"responsible_user" json:"responsible_user"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updated_at"`
}

type CriminalCase struct {
	ID          int64     `db:"id" json:"id"`
	CaseID      string    `db:"case_id" json:"case_id"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	CaseType    string    `db:"case_type" json:"case_type"`
}

type Gender struct {
	Code  string `db:"code" json:"code"`
	Label string `db:"label" json:"label"`
}

type IdentityDocument struct {
	ID             int64          `db:"id" json:"id"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	DocumentType   string         `db:"document_type" json:"document_type"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	Cpf            sql.NullString `db:"cpf" json:"cpf"`
}

type IdentityRegister struct {
	ID             int64                 `db:"id" json:"id"`
	DocumentID     int64                 `db:"document_id" json:"document_id"`
	RegisterNumber string                `db:"register_number" json:"register_number"`
	CreatedAt      time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time             `db:"updated_at" json:"updated_at"`
	Name           string                `db:"name" json:"name"`
	Parent1Name    string                `db:"parent_1_name" json:"parent_1_name"`
	Parent1Gender  string                `db:"parent_1_gender" json:"parent_1_gender"`
	Parent2Name    string                `db:"parent_2_name" json:"parent_2_name"`
	Parent2Gender  string                `db:"parent_2_gender" json:"parent_2_gender"`
	DataNascimento sql.NullString        `db:"data_nascimento" json:"data_nascimento"`
	NistPath       sql.NullString        `db:"nist_path" json:"nist_path"`
	StorageRef     sql.NullString        `db:"storage_ref" json:"storage_ref"`
	Meta           pqtype.NullRawMessage `db:"meta" json:"meta"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	Nome         string    `db:"nome" json:"nome"`
	UltimoNome   string    `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string    `db:"matricula" json:"matricula"`
	Cargo        string    `db:"cargo" json:"cargo"`
	Username     string    `db:"username" json:"username"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
