// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countCriminalCases = `-- name: CountCriminalCases :one
SELECT COUNT(*) FROM criminal_cases
`

func (q *Queries) CountCriminalCases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCriminalCases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, ultimo_nome, matricula, cargo, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nome, ultimo_nome, matricula, cargo, username, email
`

type CreateUserParams struct {
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.UltimoNome,
		arg.Matricula,
		arg.Cargo,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByMatricula = `-- name: GetUserByMatricula :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email, password_hash
FROM users
WHERE matricula = $1
`

type GetUserByMatriculaRow struct {
	ID           int64  `db:"id" json:"id"`
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserByMatricula(ctx context.Context, matricula string) (GetUserByMatriculaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByMatricula, matricula)
	var i GetUserByMatriculaRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listComparisons = `-- name: ListComparisons :many
SELECT evidence_a, evidence_b, case_type, comparison_type, responsible_user
FROM comparisons
ORDER BY evidence_a, evidence_b
LIMIT $1 OFFSET $2
`

type ListComparisonsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListComparisonsRow struct {
	EvidenceA       string         `db:"evidence_a" json:"evidence_a"`
	EvidenceB       string         `db:"evidence_b" json:"evidence_b"`
	CaseType        string         `db:"case_type" json:"case_type"`
	ComparisonType  string         `db:"comparison_type" json:"comparison_type"`
	ResponsibleUser sql.NullString `db:"responsible_user" json:"responsible_user"`
}

func (q *Queries) ListComparisons(ctx context.Context, arg ListComparisonsParams) ([]ListComparisonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComparisons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComparisonsRow
	for rows.Next() {
		var i ListComparisonsRow
		if err := rows.Scan(
			&i.EvidenceA,
			&i.EvidenceB,
			&i.CaseType,
			&i.ComparisonType,
			&i.ResponsibleUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCriminalCases = `-- name: ListCriminalCases :many
SELECT case_id, case_type, description
FROM criminal_cases
ORDER BY case_id
LIMIT $1 OFFSET $2
`

type ListCriminalCasesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCriminalCasesRow struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) ListCriminalCases(ctx context.Context, arg ListCriminalCasesParams) ([]ListCriminalCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCriminalCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCriminalCasesRow
	for rows.Next() {
		var i ListCriminalCasesRow
		if err := rows.Scan(&i.CaseID, &i.CaseType, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComparison = `-- name: UpsertComparison :exec
INSERT INTO comparisons
    (evidence_a, evidence_b, case_type, comparison_type, responsible_user)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (evidence_a, evidence_b) DO UPDATE SET
    case_type = EXCLUDED.case_type,
    comparison_type = EXCLUDED.comparison_type,
    responsible_user = EXCLUDED.responsible_user,
    updated_at = NOW()
`

type UpsertComparisonParams struct {
	EvidenceA       string         `db:"evidence_a" json:"evidence_a"`
	EvidenceB       string         `db:"evidence_b" json:"evidence_b"`
	CaseType        string         `db:"case_type" json:"case_type"`
	ComparisonType  string         `db:"comparison_type" json:"comparison_type"`
	ResponsibleUser sql.NullString `db:"responsible_user" json:"responsible_user"`
}

func (q *Queries) UpsertComparison(ctx context.Context, arg UpsertComparisonParams) error {
	_, err := q.db.ExecContext(ctx, upsertComparison,
		arg.EvidenceA,
		arg.EvidenceB,
		arg.CaseType,
		arg.ComparisonType,
		arg.ResponsibleUser,
	)
	return err
}

const upsertCriminalCase = `-- name: UpsertCriminalCase :exec
INSERT INTO criminal_cases
    (case_id, case_type, description)
VALUES ($1, $2, $3)
ON CONFLICT (case_id) DO UPDATE SET
    case_type = EXCLUDED.case_type,
    description = EXCLUDED.description,
    updated_at = NOW()
`

type UpsertCriminalCaseParams struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertCriminalCase(ctx context.Context, arg UpsertCriminalCaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCriminalCase, arg.CaseID, arg.CaseType, arg.Description)
	return err
}
