// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countCriminalCases = `-- name: CountCriminalCases :one
SELECT COUNT(*) FROM criminal_cases
`

func (q *Queries) CountCriminalCases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCriminalCases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, ultimo_nome, matricula, cargo, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nome, ultimo_nome, matricula, cargo, username, email
`

type CreateUserParams struct {
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.UltimoNome,
		arg.Matricula,
		arg.Cargo,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const findNearestFeatureEmbeddings = `-- name: FindNearestFeatureEmbeddings :many
SELECT fe.id, fe.biometricfeature_id, fe.embedding <=> $1::vector AS distance
FROM feature_embeddings fe
WHERE fe.embedding_type = $2 AND fe.id != $3
ORDER BY fe.embedding <=> $1::vector
LIMIT $4
`

type FindNearestFeatureEmbeddingsParams struct {
	Embedding     interface{} `db:"embedding" json:"embedding"`
	EmbeddingType string      `db:"embedding_type" json:"embedding_type"`
	ExcludeID     int64       `db:"exclude_id" json:"exclude_id"`
	ResultLimit   int32       `db:"result_limit" json:"result_limit"`
}

type FindNearestFeatureEmbeddingsRow struct {
	ID                 int64       `db:"id" json:"id"`
	BiometricfeatureID int64       `db:"biometricfeature_id" json:"biometricfeature_id"`
	Distance           interface{} `db:"distance" json:"distance"`
}

func (q *Queries) FindNearestFeatureEmbeddings(ctx context.Context, arg FindNearestFeatureEmbeddingsParams) ([]FindNearestFeatureEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, findNearestFeatureEmbeddings,
		arg.Embedding,
		arg.EmbeddingType,
		arg.ExcludeID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNearestFeatureEmbeddingsRow
	for rows.Next() {
		var i FindNearestFeatureEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.BiometricfeatureID, &i.Distance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCriminalCaseByCaseID = `-- name: GetCriminalCaseByCaseID :one
SELECT id, case_id, case_type, description
FROM criminal_cases
WHERE case_id = $1
`

type GetCriminalCaseByCaseIDRow struct {
	ID          int64  `db:"id" json:"id"`
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) GetCriminalCaseByCaseID(ctx context.Context, caseID string) (GetCriminalCaseByCaseIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCriminalCaseByCaseID, caseID)
	var i GetCriminalCaseByCaseIDRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.CaseType,
		&i.Description,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByMatricula = `-- name: GetUserByMatricula :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email, password_hash
FROM users
WHERE matricula = $1
`

type GetUserByMatriculaRow struct {
	ID           int64  `db:"id" json:"id"`
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserByMatricula(ctx context.Context, matricula string) (GetUserByMatriculaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByMatricula, matricula)
	var i GetUserByMatriculaRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const insertBiometricDecision = `-- name: InsertBiometricDecision :one
INSERT INTO biometric_decisions
    (feature_a_id, feature_b_id, modality, role, decision, system_source, username, confidence, threshold, notes,
     comparison_type, related_reference, related_reference_kind, responsible_user)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, feature_a_id, feature_b_id, modality, role, decision, system_source, username, confidence, threshold, notes,
    comparison_type, related_reference, related_reference_kind, responsible_user, decided_at, created_at
`

type InsertBiometricDecisionParams struct {
	FeatureAID           string          `db:"feature_a_id" json:"feature_a_id"`
	FeatureBID           string          `db:"feature_b_id" json:"feature_b_id"`
	Modality             string          `db:"modality" json:"modality"`
	Role                 string          `db:"role" json:"role"`
	Decision             string          `db:"decision" json:"decision"`
	SystemSource         sql.NullString  `db:"system_source" json:"system_source"`
	Username             sql.NullString  `db:"username" json:"username"`
	Confidence           sql.NullFloat64 `db:"confidence" json:"confidence"`
	Threshold            sql.NullFloat64 `db:"threshold" json:"threshold"`
	Notes                sql.NullString  `db:"notes" json:"notes"`
	ComparisonType       sql.NullString  `db:"comparison_type" json:"comparison_type"`
	RelatedReference     sql.NullString  `db:"related_reference" json:"related_reference"`
	RelatedReferenceKind sql.NullString  `db:"related_reference_kind" json:"related_reference_kind"`
	ResponsibleUser      sql.NullString  `db:"responsible_user" json:"responsible_user"`
}

type InsertBiometricDecisionRow struct {
	ID                   int64           `db:"id" json:"id"`
	FeatureAID           string          `db:"feature_a_id" json:"feature_a_id"`
	FeatureBID           string          `db:"feature_b_id" json:"feature_b_id"`
	Modality             string          `db:"modality" json:"modality"`
	Role                 string          `db:"role" json:"role"`
	Decision             string          `db:"decision" json:"decision"`
	SystemSource         sql.NullString  `db:"system_source" json:"system_source"`
	Username             sql.NullString  `db:"username" json:"username"`
	Confidence           sql.NullFloat64 `db:"confidence" json:"confidence"`
	Threshold            sql.NullFloat64 `db:"threshold" json:"threshold"`
	Notes                sql.NullString  `db:"notes" json:"notes"`
	ComparisonType       sql.NullString  `db:"comparison_type" json:"comparison_type"`
	RelatedReference     sql.NullString  `db:"related_reference" json:"related_reference"`
	RelatedReferenceKind sql.NullString  `db:"related_reference_kind" json:"related_reference_kind"`
	ResponsibleUser      sql.NullString  `db:"responsible_user" json:"responsible_user"`
	DecidedAt            time.Time       `db:"decided_at" json:"decided_at"`
	CreatedAt            time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertBiometricDecision(ctx context.Context, arg InsertBiometricDecisionParams) (InsertBiometricDecisionRow, error) {
	row := q.db.QueryRowContext(ctx, insertBiometricDecision,
		arg.FeatureAID,
		arg.FeatureBID,
		arg.Modality,
		arg.Role,
		arg.Decision,
		arg.SystemSource,
		arg.Username,
		arg.Confidence,
		arg.Threshold,
		arg.Notes,
		arg.ComparisonType,
		arg.RelatedReference,
		arg.RelatedReferenceKind,
		arg.ResponsibleUser,
	)
	var i InsertBiometricDecisionRow
	err := row.Scan(
		&i.ID,
		&i.FeatureAID,
		&i.FeatureBID,
		&i.Modality,
		&i.Role,
		&i.Decision,
		&i.SystemSource,
		&i.Username,
		&i.Confidence,
		&i.Threshold,
		&i.Notes,
		&i.ComparisonType,
		&i.RelatedReference,
		&i.RelatedReferenceKind,
		&i.ResponsibleUser,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCaseDecision = `-- name: InsertCaseDecision :one
INSERT INTO case_decisions (criminal_case_id, decision, system_source, username, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, criminal_case_id, decision, system_source, username, notes, decided_at, created_at
`

type InsertCaseDecisionParams struct {
	CriminalCaseID int64          `db:"criminal_case_id" json:"criminal_case_id"`
	Decision       string         `db:"decision" json:"decision"`
	SystemSource   sql.NullString `db:"system_source" json:"system_source"`
	Username       sql.NullString `db:"username" json:"username"`
	Notes          sql.NullString `db:"notes" json:"notes"`
}

func (q *Queries) InsertCaseDecision(ctx context.Context, arg InsertCaseDecisionParams) (CaseDecision, error) {
	row := q.db.QueryRowContext(ctx, insertCaseDecision,
		arg.CriminalCaseID,
		arg.Decision,
		arg.SystemSource,
		arg.Username,
		arg.Notes,
	)
	var i CaseDecision
	err := row.Scan(
		&i.ID,
		&i.CriminalCaseID,
		&i.Decision,
		&i.SystemSource,
		&i.Username,
		&i.Notes,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBiometricDecisions = `-- name: ListBiometricDecisions :many
SELECT feature_a_id, feature_b_id, modality, role, decision, system_source, username, confidence
FROM biometric_decisions
ORDER BY feature_a_id, feature_b_id, decided_at
`

type ListBiometricDecisionsRow struct {
	FeatureAID   string          `db:"feature_a_id" json:"feature_a_id"`
	FeatureBID   string          `db:"feature_b_id" json:"feature_b_id"`
	Modality     string          `db:"modality" json:"modality"`
	Role         string          `db:"role" json:"role"`
	Decision     string          `db:"decision" json:"decision"`
	SystemSource sql.NullString  `db:"system_source" json:"system_source"`
	Username     sql.NullString  `db:"username" json:"username"`
	Confidence   sql.NullFloat64 `db:"confidence" json:"confidence"`
}

func (q *Queries) ListBiometricDecisions(ctx context.Context) ([]ListBiometricDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBiometricDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBiometricDecisionsRow
	for rows.Next() {
		var i ListBiometricDecisionsRow
		if err := rows.Scan(
			&i.FeatureAID,
			&i.FeatureBID,
			&i.Modality,
			&i.Role,
			&i.Decision,
			&i.SystemSource,
			&i.Username,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBiometricFeatures = `-- name: ListBiometricFeatures :many
SELECT id, feature_type, provenance, identity_file_id, case_trace_id
FROM biometricfeature
ORDER BY id
`

type ListBiometricFeaturesRow struct {
	ID             int64         `db:"id" json:"id"`
	FeatureType    string        `db:"feature_type" json:"feature_type"`
	Provenance     string        `db:"provenance" json:"provenance"`
	IdentityFileID sql.NullInt64 `db:"identity_file_id" json:"identity_file_id"`
	CaseTraceID    sql.NullInt64 `db:"case_trace_id" json:"case_trace_id"`
}

func (q *Queries) ListBiometricFeatures(ctx context.Context) ([]ListBiometricFeaturesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBiometricFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBiometricFeaturesRow
	for rows.Next() {
		var i ListBiometricFeaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureType,
			&i.Provenance,
			&i.IdentityFileID,
			&i.CaseTraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaseDecisionsByCriminalCase = `-- name: ListCaseDecisionsByCriminalCase :many
SELECT id, criminal_case_id, decision, system_source, username, notes, decided_at, created_at
FROM case_decisions
WHERE criminal_case_id = $1
ORDER BY decided_at
`

func (q *Queries) ListCaseDecisionsByCriminalCase(ctx context.Context, criminalCaseID int64) ([]CaseDecision, error) {
	rows, err := q.db.QueryContext(ctx, listCaseDecisionsByCriminalCase, criminalCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaseDecision
	for rows.Next() {
		var i CaseDecision
		if err := rows.Scan(
			&i.ID,
			&i.CriminalCaseID,
			&i.Decision,
			&i.SystemSource,
			&i.Username,
			&i.Notes,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCriminalCases = `-- name: ListCriminalCases :many
SELECT case_id, case_type, description
FROM criminal_cases
ORDER BY case_id
LIMIT $1 OFFSET $2
`

type ListCriminalCasesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCriminalCasesRow struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) ListCriminalCases(ctx context.Context, arg ListCriminalCasesParams) ([]ListCriminalCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCriminalCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCriminalCasesRow
	for rows.Next() {
		var i ListCriminalCasesRow
		if err := rows.Scan(&i.CaseID, &i.CaseType, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedFeatureEmbeddings = `-- name: ListUnmatchedFeatureEmbeddings :many
SELECT id, biometricfeature_id, embedding_type, embedding::text AS embedding, model_version
FROM feature_embeddings
WHERE embedding_type = $1 AND matched_at IS NULL
ORDER BY id
`

type ListUnmatchedFeatureEmbeddingsRow struct {
	ID                 int64          `db:"id" json:"id"`
	BiometricfeatureID int64          `db:"biometricfeature_id" json:"biometricfeature_id"`
	EmbeddingType      string         `db:"embedding_type" json:"embedding_type"`
	Embedding          string         `db:"embedding" json:"embedding"`
	ModelVersion       sql.NullString `db:"model_version" json:"model_version"`
}

func (q *Queries) ListUnmatchedFeatureEmbeddings(ctx context.Context, embeddingType string) ([]ListUnmatchedFeatureEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedFeatureEmbeddings, embeddingType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnmatchedFeatureEmbeddingsRow
	for rows.Next() {
		var i ListUnmatchedFeatureEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.BiometricfeatureID,
			&i.EmbeddingType,
			&i.Embedding,
			&i.ModelVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeatureEmbeddingMatched = `-- name: MarkFeatureEmbeddingMatched :exec
UPDATE feature_embeddings SET matched_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkFeatureEmbeddingMatched(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markFeatureEmbeddingMatched, id)
	return err
}

const updateCriminalCaseDescription = `-- name: UpdateCriminalCaseDescription :exec
UPDATE criminal_cases SET description = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCriminalCaseDescriptionParams struct {
	ID          int64  `db:"id" json:"id"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpdateCriminalCaseDescription(ctx context.Context, arg UpdateCriminalCaseDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateCriminalCaseDescription, arg.ID, arg.Description)
	return err
}

const upsertBiometricFeatureFromCaseTrace = `-- name: UpsertBiometricFeatureFromCaseTrace :one
INSERT INTO biometricfeature (feature_type, provenance, case_trace_id)
VALUES ($1, $2, $3)
ON CONFLICT (case_trace_id) DO UPDATE SET
    feature_type = EXCLUDED.feature_type,
    provenance = EXCLUDED.provenance,
    updated_at = NOW()
RETURNING id
`

type UpsertBiometricFeatureFromCaseTraceParams struct {
	FeatureType string        `db:"feature_type" json:"feature_type"`
	Provenance  string        `db:"provenance" json:"provenance"`
	CaseTraceID sql.NullInt64 `db:"case_trace_id" json:"case_trace_id"`
}

func (q *Queries) UpsertBiometricFeatureFromCaseTrace(ctx context.Context, arg UpsertBiometricFeatureFromCaseTraceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertBiometricFeatureFromCaseTrace, arg.FeatureType, arg.Provenance, arg.CaseTraceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertBiometricFeatureFromIdentityFile = `-- name: UpsertBiometricFeatureFromIdentityFile :one
INSERT INTO biometricfeature (feature_type, provenance, identity_file_id)
VALUES ($1, $2, $3)
ON CONFLICT (identity_file_id) DO UPDATE SET
    feature_type = EXCLUDED.feature_type,
    provenance = EXCLUDED.provenance,
    updated_at = NOW()
RETURNING id
`

type UpsertBiometricFeatureFromIdentityFileParams struct {
	FeatureType    string        `db:"feature_type" json:"feature_type"`
	Provenance     string        `db:"provenance" json:"provenance"`
	IdentityFileID sql.NullInt64 `db:"identity_file_id" json:"identity_file_id"`
}

func (q *Queries) UpsertBiometricFeatureFromIdentityFile(ctx context.Context, arg UpsertBiometricFeatureFromIdentityFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertBiometricFeatureFromIdentityFile, arg.FeatureType, arg.Provenance, arg.IdentityFileID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCaseCodification = `-- name: UpsertCaseCodification :one
INSERT INTO case_codifications (trace_id, sequence, codification_type)
VALUES ($1, $2, $3)
ON CONFLICT (trace_id, sequence) DO UPDATE SET
    codification_type = EXCLUDED.codification_type,
    updated_at = NOW()
RETURNING id
`

type UpsertCaseCodificationParams struct {
	TraceID          int64  `db:"trace_id" json:"trace_id"`
	Sequence         int16  `db:"sequence" json:"sequence"`
	CodificationType string `db:"codification_type" json:"codification_type"`
}

func (q *Queries) UpsertCaseCodification(ctx context.Context, arg UpsertCaseCodificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCaseCodification, arg.TraceID, arg.Sequence, arg.CodificationType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCaseEvidence = `-- name: UpsertCaseEvidence :one
INSERT INTO case_evidences (criminal_case_id, sequence, case_file_id, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (criminal_case_id, sequence) DO UPDATE SET
    case_file_id = EXCLUDED.case_file_id,
    description = EXCLUDED.description,
    updated_at = NOW()
RETURNING id
`

type UpsertCaseEvidenceParams struct {
	CriminalCaseID int64          `db:"criminal_case_id" json:"criminal_case_id"`
	Sequence       int16          `db:"sequence" json:"sequence"`
	CaseFileID     sql.NullInt64  `db:"case_file_id" json:"case_file_id"`
	Description    sql.NullString `db:"description" json:"description"`
}

func (q *Queries) UpsertCaseEvidence(ctx context.Context, arg UpsertCaseEvidenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCaseEvidence,
		arg.CriminalCaseID,
		arg.Sequence,
		arg.CaseFileID,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCaseFile = `-- name: UpsertCaseFile :one
INSERT INTO case_files (criminal_case_id, category, media_type, hash_id, filename, source_path, storage_ref, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (criminal_case_id, category, hash_id) DO UPDATE SET
    media_type = EXCLUDED.media_type,
    filename = EXCLUDED.filename,
    source_path = EXCLUDED.source_path,
    storage_ref = EXCLUDED.storage_ref,
    content_type = EXCLUDED.content_type,
    size_bytes = EXCLUDED.size_bytes,
    updated_at = NOW()
RETURNING id
`

type UpsertCaseFileParams struct {
	CriminalCaseID int64          `db:"criminal_case_id" json:"criminal_case_id"`
	Category       string         `db:"category" json:"category"`
	MediaType      sql.NullString `db:"media_type" json:"media_type"`
	HashID         sql.NullString `db:"hash_id" json:"hash_id"`
	Filename       sql.NullString `db:"filename" json:"filename"`
	SourcePath     sql.NullString `db:"source_path" json:"source_path"`
	StorageRef     sql.NullString `db:"storage_ref" json:"storage_ref"`
	ContentType    sql.NullString `db:"content_type" json:"content_type"`
	SizeBytes      sql.NullInt64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) UpsertCaseFile(ctx context.Context, arg UpsertCaseFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCaseFile,
		arg.CriminalCaseID,
		arg.Category,
		arg.MediaType,
		arg.HashID,
		arg.Filename,
		arg.SourcePath,
		arg.StorageRef,
		arg.ContentType,
		arg.SizeBytes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCaseTrace = `-- name: UpsertCaseTrace :one
INSERT INTO case_traces (evidence_id, sequence, trace_type, box_x1, box_y1, box_x2, box_y2, detection_score, case_file_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (evidence_id, sequence) DO UPDATE SET
    trace_type = EXCLUDED.trace_type,
    box_x1 = EXCLUDED.box_x1,
    box_y1 = EXCLUDED.box_y1,
    box_x2 = EXCLUDED.box_x2,
    box_y2 = EXCLUDED.box_y2,
    detection_score = EXCLUDED.detection_score,
    case_file_id = EXCLUDED.case_file_id,
    updated_at = NOW()
RETURNING id
`

type UpsertCaseTraceParams struct {
	EvidenceID     int64           `db:"evidence_id" json:"evidence_id"`
	Sequence       int16           `db:"sequence" json:"sequence"`
	TraceType      string          `db:"trace_type" json:"trace_type"`
	BoxX1          sql.NullFloat64 `db:"box_x1" json:"box_x1"`
	BoxY1          sql.NullFloat64 `db:"box_y1" json:"box_y1"`
	BoxX2          sql.NullFloat64 `db:"box_x2" json:"box_x2"`
	BoxY2          sql.NullFloat64 `db:"box_y2" json:"box_y2"`
	DetectionScore sql.NullFloat64 `db:"detection_score" json:"detection_score"`
	CaseFileID     sql.NullInt64   `db:"case_file_id" json:"case_file_id"`
}

func (q *Queries) UpsertCaseTrace(ctx context.Context, arg UpsertCaseTraceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCaseTrace,
		arg.EvidenceID,
		arg.Sequence,
		arg.TraceType,
		arg.BoxX1,
		arg.BoxY1,
		arg.BoxX2,
		arg.BoxY2,
		arg.DetectionScore,
		arg.CaseFileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCriminalCase = `-- name: UpsertCriminalCase :one
INSERT INTO criminal_cases (case_id, case_type, description)
VALUES ($1, $2, $3)
ON CONFLICT (case_id) DO UPDATE SET
    case_type = EXCLUDED.case_type,
    description = EXCLUDED.description,
    updated_at = NOW()
RETURNING id
`

type UpsertCriminalCaseParams struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertCriminalCase(ctx context.Context, arg UpsertCriminalCaseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCriminalCase, arg.CaseID, arg.CaseType, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertFeatureEmbedding = `-- name: UpsertFeatureEmbedding :one
INSERT INTO feature_embeddings (biometricfeature_id, embedding_type, embedding, model_version)
VALUES ($1, $2, $3::vector, $4)
ON CONFLICT (biometricfeature_id, embedding_type) DO UPDATE SET
    embedding = EXCLUDED.embedding,
    model_version = EXCLUDED.model_version,
    matched_at = NULL,
    updated_at = NOW()
RETURNING id
`

type UpsertFeatureEmbeddingParams struct {
	BiometricfeatureID int64          `db:"biometricfeature_id" json:"biometricfeature_id"`
	EmbeddingType      string         `db:"embedding_type" json:"embedding_type"`
	Embedding          interface{}    `db:"embedding" json:"embedding"`
	ModelVersion       sql.NullString `db:"model_version" json:"model_version"`
}

// embedding is passed as pgvector's text input format ("[v1,v2,...]") and cast explicitly,
// so no pgvector-aware driver/codec is needed -- consistent with this package's plain
// database/sql usage elsewhere.
func (q *Queries) UpsertFeatureEmbedding(ctx context.Context, arg UpsertFeatureEmbeddingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertFeatureEmbedding,
		arg.BiometricfeatureID,
		arg.EmbeddingType,
		arg.Embedding,
		arg.ModelVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertIdentityDocument = `-- name: UpsertIdentityDocument :one
INSERT INTO identity_document (person_id, document_number, document_type, cpf)
VALUES ($1, $2, $3, $4)
ON CONFLICT (document_type, document_number) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    cpf = EXCLUDED.cpf,
    updated_at = NOW()
RETURNING id
`

type UpsertIdentityDocumentParams struct {
	PersonID       sql.NullInt64  `db:"person_id" json:"person_id"`
	DocumentNumber string         `db:"document_number" json:"document_number"`
	DocumentType   string         `db:"document_type" json:"document_type"`
	Cpf            sql.NullString `db:"cpf" json:"cpf"`
}

func (q *Queries) UpsertIdentityDocument(ctx context.Context, arg UpsertIdentityDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertIdentityDocument,
		arg.PersonID,
		arg.DocumentNumber,
		arg.DocumentType,
		arg.Cpf,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertIdentityFile = `-- name: UpsertIdentityFile :one
INSERT INTO identity_file (register_id, file_type, sequence, source_path, storage_ref, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (register_id, file_type, sequence) DO UPDATE SET
    source_path = EXCLUDED.source_path,
    storage_ref = EXCLUDED.storage_ref,
    content_type = EXCLUDED.content_type,
    size_bytes = EXCLUDED.size_bytes,
    updated_at = NOW()
RETURNING id
`

type UpsertIdentityFileParams struct {
	RegisterID  int64          `db:"register_id" json:"register_id"`
	FileType    string         `db:"file_type" json:"file_type"`
	Sequence    int16          `db:"sequence" json:"sequence"`
	SourcePath  string         `db:"source_path" json:"source_path"`
	StorageRef  string         `db:"storage_ref" json:"storage_ref"`
	ContentType sql.NullString `db:"content_type" json:"content_type"`
	SizeBytes   sql.NullInt64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) UpsertIdentityFile(ctx context.Context, arg UpsertIdentityFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertIdentityFile,
		arg.RegisterID,
		arg.FileType,
		arg.Sequence,
		arg.SourcePath,
		arg.StorageRef,
		arg.ContentType,
		arg.SizeBytes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertIdentityRegister = `-- name: UpsertIdentityRegister :one
INSERT INTO identity_register
    (document_id, register_number, name, parent_1_name, parent_1_gender, parent_2_name, parent_2_gender, data_nascimento, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (register_number) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    name = EXCLUDED.name,
    parent_1_name = EXCLUDED.parent_1_name,
    parent_1_gender = EXCLUDED.parent_1_gender,
    parent_2_name = EXCLUDED.parent_2_name,
    parent_2_gender = EXCLUDED.parent_2_gender,
    data_nascimento = EXCLUDED.data_nascimento,
    meta = EXCLUDED.meta,
    updated_at = NOW()
RETURNING id
`

type UpsertIdentityRegisterParams struct {
	DocumentID     int64                 `db:"document_id" json:"document_id"`
	RegisterNumber string                `db:"register_number" json:"register_number"`
	Name           string                `db:"name" json:"name"`
	Parent1Name    string                `db:"parent_1_name" json:"parent_1_name"`
	Parent1Gender  string                `db:"parent_1_gender" json:"parent_1_gender"`
	Parent2Name    string                `db:"parent_2_name" json:"parent_2_name"`
	Parent2Gender  string                `db:"parent_2_gender" json:"parent_2_gender"`
	DataNascimento sql.NullString        `db:"data_nascimento" json:"data_nascimento"`
	Meta           pqtype.NullRawMessage `db:"meta" json:"meta"`
}

func (q *Queries) UpsertIdentityRegister(ctx context.Context, arg UpsertIdentityRegisterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertIdentityRegister,
		arg.DocumentID,
		arg.RegisterNumber,
		arg.Name,
		arg.Parent1Name,
		arg.Parent1Gender,
		arg.Parent2Name,
		arg.Parent2Gender,
		arg.DataNascimento,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertPerson = `-- name: UpsertPerson :one
INSERT INTO person (person_id, meta)
VALUES ($1, $2)
ON CONFLICT (person_id) DO UPDATE SET
    meta = EXCLUDED.meta,
    updated_at = NOW()
RETURNING id
`

type UpsertPersonParams struct {
	PersonID string                `db:"person_id" json:"person_id"`
	Meta     pqtype.NullRawMessage `db:"meta" json:"meta"`
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertPerson, arg.PersonID, arg.Meta)
	var id int64
	err := row.Scan(&id)
	return id, err
}
