// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const countCriminalCases = `-- name: CountCriminalCases :one
SELECT COUNT(*) FROM criminal_cases
`

func (q *Queries) CountCriminalCases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCriminalCases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, ultimo_nome, matricula, cargo, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nome, ultimo_nome, matricula, cargo, username, email
`

type CreateUserParams struct {
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.UltimoNome,
		arg.Matricula,
		arg.Cargo,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByMatricula = `-- name: GetUserByMatricula :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email, password_hash
FROM users
WHERE matricula = $1
`

type GetUserByMatriculaRow struct {
	ID           int64  `db:"id" json:"id"`
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserByMatricula(ctx context.Context, matricula string) (GetUserByMatriculaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByMatricula, matricula)
	var i GetUserByMatriculaRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listComparisons = `-- name: ListComparisons :many
SELECT evidence_a, evidence_b, case_type, comparison_type, responsible_user
FROM comparisons
ORDER BY evidence_a, evidence_b
LIMIT $1 OFFSET $2
`

type ListComparisonsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListComparisonsRow struct {
	EvidenceA       string         `db:"evidence_a" json:"evidence_a"`
	EvidenceB       string         `db:"evidence_b" json:"evidence_b"`
	CaseType        string         `db:"case_type" json:"case_type"`
	ComparisonType  string         `db:"comparison_type" json:"comparison_type"`
	ResponsibleUser sql.NullString `db:"responsible_user" json:"responsible_user"`
}

func (q *Queries) ListComparisons(ctx context.Context, arg ListComparisonsParams) ([]ListComparisonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComparisons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComparisonsRow
	for rows.Next() {
		var i ListComparisonsRow
		if err := rows.Scan(
			&i.EvidenceA,
			&i.EvidenceB,
			&i.CaseType,
			&i.ComparisonType,
			&i.ResponsibleUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCriminalCases = `-- name: ListCriminalCases :many
SELECT case_id, case_type, description
FROM criminal_cases
ORDER BY case_id
LIMIT $1 OFFSET $2
`

type ListCriminalCasesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCriminalCasesRow struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) ListCriminalCases(ctx context.Context, arg ListCriminalCasesParams) ([]ListCriminalCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCriminalCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCriminalCasesRow
	for rows.Next() {
		var i ListCriminalCasesRow
		if err := rows.Scan(&i.CaseID, &i.CaseType, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectComparison = `-- name: RejectComparison :exec
UPDATE comparisons SET status = 'rejected', updated_at = NOW()
WHERE evidence_a = $1 AND evidence_b = $2
`

type RejectComparisonParams struct {
	EvidenceA string `db:"evidence_a" json:"evidence_a"`
	EvidenceB string `db:"evidence_b" json:"evidence_b"`
}

func (q *Queries) RejectComparison(ctx context.Context, arg RejectComparisonParams) error {
	_, err := q.db.ExecContext(ctx, rejectComparison, arg.EvidenceA, arg.EvidenceB)
	return err
}

const upsertCodification = `-- name: UpsertCodification :exec
INSERT INTO codifications (trace_id, format, version, payload_ref)
VALUES ($1, $2, $3, $4)
ON CONFLICT (trace_id, format, version) DO UPDATE SET
    payload_ref = EXCLUDED.payload_ref,
    updated_at = NOW()
`

type UpsertCodificationParams struct {
	TraceID    string         `db:"trace_id" json:"trace_id"`
	Format     string         `db:"format" json:"format"`
	Version    string         `db:"version" json:"version"`
	PayloadRef sql.NullString `db:"payload_ref" json:"payload_ref"`
}

func (q *Queries) UpsertCodification(ctx context.Context, arg UpsertCodificationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCodification,
		arg.TraceID,
		arg.Format,
		arg.Version,
		arg.PayloadRef,
	)
	return err
}

const upsertComparison = `-- name: UpsertComparison :exec
INSERT INTO comparisons
    (evidence_a, evidence_b, case_type, comparison_type, responsible_user)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (evidence_a, evidence_b) DO UPDATE SET
    case_type = EXCLUDED.case_type,
    comparison_type = EXCLUDED.comparison_type,
    responsible_user = EXCLUDED.responsible_user,
    updated_at = NOW()
`

type UpsertComparisonParams struct {
	EvidenceA       string         `db:"evidence_a" json:"evidence_a"`
	EvidenceB       string         `db:"evidence_b" json:"evidence_b"`
	CaseType        string         `db:"case_type" json:"case_type"`
	ComparisonType  string         `db:"comparison_type" json:"comparison_type"`
	ResponsibleUser sql.NullString `db:"responsible_user" json:"responsible_user"`
}

func (q *Queries) UpsertComparison(ctx context.Context, arg UpsertComparisonParams) error {
	_, err := q.db.ExecContext(ctx, upsertComparison,
		arg.EvidenceA,
		arg.EvidenceB,
		arg.CaseType,
		arg.ComparisonType,
		arg.ResponsibleUser,
	)
	return err
}

const upsertCriminalCase = `-- name: UpsertCriminalCase :exec
INSERT INTO criminal_cases
    (case_id, case_type, description)
VALUES ($1, $2, $3)
ON CONFLICT (case_id) DO UPDATE SET
    case_type = EXCLUDED.case_type,
    description = EXCLUDED.description,
    updated_at = NOW()
`

type UpsertCriminalCaseParams struct {
	CaseID      string `db:"case_id" json:"case_id"`
	CaseType    string `db:"case_type" json:"case_type"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertCriminalCase(ctx context.Context, arg UpsertCriminalCaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCriminalCase, arg.CaseID, arg.CaseType, arg.Description)
	return err
}

const upsertIdentification = `-- name: UpsertIdentification :exec
INSERT INTO identifications (trace_id, identity_register_id, trace_codification_id, confidence, responsible_user, source)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (trace_id, identity_register_id) DO UPDATE SET
    trace_codification_id = EXCLUDED.trace_codification_id,
    confidence = EXCLUDED.confidence,
    responsible_user = EXCLUDED.responsible_user,
    source = EXCLUDED.source,
    updated_at = NOW()
`

type UpsertIdentificationParams struct {
	TraceID             string          `db:"trace_id" json:"trace_id"`
	IdentityRegisterID  int64           `db:"identity_register_id" json:"identity_register_id"`
	TraceCodificationID sql.NullInt64   `db:"trace_codification_id" json:"trace_codification_id"`
	Confidence          sql.NullFloat64 `db:"confidence" json:"confidence"`
	ResponsibleUser     sql.NullString  `db:"responsible_user" json:"responsible_user"`
	Source              sql.NullString  `db:"source" json:"source"`
}

func (q *Queries) UpsertIdentification(ctx context.Context, arg UpsertIdentificationParams) error {
	_, err := q.db.ExecContext(ctx, upsertIdentification,
		arg.TraceID,
		arg.IdentityRegisterID,
		arg.TraceCodificationID,
		arg.Confidence,
		arg.ResponsibleUser,
		arg.Source,
	)
	return err
}

const upsertPerson = `-- name: UpsertPerson :exec
INSERT INTO person (person_id, meta)
VALUES ($1, $2)
ON CONFLICT (person_id) DO UPDATE SET
    meta = EXCLUDED.meta,
    updated_at = NOW()
`

type UpsertPersonParams struct {
	PersonID string                `db:"person_id" json:"person_id"`
	Meta     pqtype.NullRawMessage `db:"meta" json:"meta"`
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, upsertPerson, arg.PersonID, arg.Meta)
	return err
}
