// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type FingerprintCase struct {
	ID                   int64          `db:"id" json:"id"`
	SourceDataset        string         `db:"source_dataset" json:"source_dataset"`
	SourceRow            int64          `db:"source_row" json:"source_row"`
	CaseID               string         `db:"case_id" json:"case_id"`
	Description          string         `db:"description" json:"description"`
	ResponsibleUser      sql.NullString `db:"responsible_user" json:"responsible_user"`
	ComparisonType       sql.NullString `db:"comparison_type" json:"comparison_type"`
	RelatedReference     sql.NullString `db:"related_reference" json:"related_reference"`
	RelatedReferenceKind sql.NullString `db:"related_reference_kind" json:"related_reference_kind"`
	CreatedAt            time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updated_at"`
}

type InfobioEnrollment struct {
	Nif                 string         `db:"nif" json:"nif"`
	NumeroIdentificacao sql.NullString `db:"numero_identificacao" json:"numero_identificacao"`
	Rin                 sql.NullString `db:"rin" json:"rin"`
	Nome                sql.NullString `db:"nome" json:"nome"`
	DataNascimento      sql.NullString `db:"data_nascimento" json:"data_nascimento"`
	Cpf                 sql.NullString `db:"cpf" json:"cpf"`
	NomePai             sql.NullString `db:"nome_pai" json:"nome_pai"`
	NomeMae             sql.NullString `db:"nome_mae" json:"nome_mae"`
	ContainerNumber     sql.NullString `db:"container_number" json:"container_number"`
	NistPath            sql.NullString `db:"nist_path" json:"nist_path"`
	StorageRef          sql.NullString `db:"storage_ref" json:"storage_ref"`
	Source              string         `db:"source" json:"source"`
	ConfirmedAt         time.Time      `db:"confirmed_at" json:"confirmed_at"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time      `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	Nome         string    `db:"nome" json:"nome"`
	UltimoNome   string    `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string    `db:"matricula" json:"matricula"`
	Cargo        string    `db:"cargo" json:"cargo"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	Username     string    `db:"username" json:"username"`
	Email        string    `db:"email" json:"email"`
}
