// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countFingerprintCases = `-- name: CountFingerprintCases :one
SELECT COUNT(*) FROM fingerprint_cases
`

func (q *Queries) CountFingerprintCases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFingerprintCases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, ultimo_nome, matricula, cargo, username, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nome, ultimo_nome, matricula, cargo, username, email
`

type CreateUserParams struct {
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.UltimoNome,
		arg.Matricula,
		arg.Cargo,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getInfoBioEnrollment = `-- name: GetInfoBioEnrollment :one
SELECT nif, numero_identificacao, rin, nome, data_nascimento, cpf, nome_pai, nome_mae, container_number, nist_path, storage_ref, source, confirmed_at
FROM infobio_enrollments
WHERE nif = $1
`

type GetInfoBioEnrollmentRow struct {
	Nif                 string         `db:"nif" json:"nif"`
	NumeroIdentificacao sql.NullString `db:"numero_identificacao" json:"numero_identificacao"`
	Rin                 sql.NullString `db:"rin" json:"rin"`
	Nome                sql.NullString `db:"nome" json:"nome"`
	DataNascimento      sql.NullString `db:"data_nascimento" json:"data_nascimento"`
	Cpf                 sql.NullString `db:"cpf" json:"cpf"`
	NomePai             sql.NullString `db:"nome_pai" json:"nome_pai"`
	NomeMae             sql.NullString `db:"nome_mae" json:"nome_mae"`
	ContainerNumber     sql.NullString `db:"container_number" json:"container_number"`
	NistPath            sql.NullString `db:"nist_path" json:"nist_path"`
	StorageRef          sql.NullString `db:"storage_ref" json:"storage_ref"`
	Source              string         `db:"source" json:"source"`
	ConfirmedAt         time.Time      `db:"confirmed_at" json:"confirmed_at"`
}

func (q *Queries) GetInfoBioEnrollment(ctx context.Context, nif string) (GetInfoBioEnrollmentRow, error) {
	row := q.db.QueryRowContext(ctx, getInfoBioEnrollment, nif)
	var i GetInfoBioEnrollmentRow
	err := row.Scan(
		&i.Nif,
		&i.NumeroIdentificacao,
		&i.Rin,
		&i.Nome,
		&i.DataNascimento,
		&i.Cpf,
		&i.NomePai,
		&i.NomeMae,
		&i.ContainerNumber,
		&i.NistPath,
		&i.StorageRef,
		&i.Source,
		&i.ConfirmedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         int64  `db:"id" json:"id"`
	Nome       string `db:"nome" json:"nome"`
	UltimoNome string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula  string `db:"matricula" json:"matricula"`
	Cargo      string `db:"cargo" json:"cargo"`
	Username   string `db:"username" json:"username"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
	)
	return i, err
}

const getUserByMatricula = `-- name: GetUserByMatricula :one
SELECT id, nome, ultimo_nome, matricula, cargo, username, email, password_hash
FROM users
WHERE matricula = $1
`

type GetUserByMatriculaRow struct {
	ID           int64  `db:"id" json:"id"`
	Nome         string `db:"nome" json:"nome"`
	UltimoNome   string `db:"ultimo_nome" json:"ultimo_nome"`
	Matricula    string `db:"matricula" json:"matricula"`
	Cargo        string `db:"cargo" json:"cargo"`
	Username     string `db:"username" json:"username"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserByMatricula(ctx context.Context, matricula string) (GetUserByMatriculaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByMatricula, matricula)
	var i GetUserByMatriculaRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.UltimoNome,
		&i.Matricula,
		&i.Cargo,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listFingerprintCases = `-- name: ListFingerprintCases :many
SELECT source_dataset, source_row, case_id, description, responsible_user, comparison_type, related_reference, related_reference_kind
FROM fingerprint_cases
ORDER BY case_id, source_row
LIMIT $1 OFFSET $2
`

type ListFingerprintCasesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListFingerprintCasesRow struct {
	SourceDataset        string         `db:"source_dataset" json:"source_dataset"`
	SourceRow            int64          `db:"source_row" json:"source_row"`
	CaseID               string         `db:"case_id" json:"case_id"`
	Description          string         `db:"description" json:"description"`
	ResponsibleUser      sql.NullString `db:"responsible_user" json:"responsible_user"`
	ComparisonType       sql.NullString `db:"comparison_type" json:"comparison_type"`
	RelatedReference     sql.NullString `db:"related_reference" json:"related_reference"`
	RelatedReferenceKind sql.NullString `db:"related_reference_kind" json:"related_reference_kind"`
}

func (q *Queries) ListFingerprintCases(ctx context.Context, arg ListFingerprintCasesParams) ([]ListFingerprintCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFingerprintCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFingerprintCasesRow
	for rows.Next() {
		var i ListFingerprintCasesRow
		if err := rows.Scan(
			&i.SourceDataset,
			&i.SourceRow,
			&i.CaseID,
			&i.Description,
			&i.ResponsibleUser,
			&i.ComparisonType,
			&i.RelatedReference,
			&i.RelatedReferenceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFingerprintCase = `-- name: UpsertFingerprintCase :exec
INSERT INTO fingerprint_cases
    (source_dataset, source_row, case_id, description, responsible_user, comparison_type, related_reference, related_reference_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_dataset, case_id) DO UPDATE SET
    source_row = EXCLUDED.source_row,
    description = EXCLUDED.description,
    responsible_user = EXCLUDED.responsible_user,
    comparison_type = EXCLUDED.comparison_type,
    related_reference = EXCLUDED.related_reference,
    related_reference_kind = EXCLUDED.related_reference_kind,
    updated_at = NOW()
`

type UpsertFingerprintCaseParams struct {
	SourceDataset        string         `db:"source_dataset" json:"source_dataset"`
	SourceRow            int64          `db:"source_row" json:"source_row"`
	CaseID               string         `db:"case_id" json:"case_id"`
	Description          string         `db:"description" json:"description"`
	ResponsibleUser      sql.NullString `db:"responsible_user" json:"responsible_user"`
	ComparisonType       sql.NullString `db:"comparison_type" json:"comparison_type"`
	RelatedReference     sql.NullString `db:"related_reference" json:"related_reference"`
	RelatedReferenceKind sql.NullString `db:"related_reference_kind" json:"related_reference_kind"`
}

func (q *Queries) UpsertFingerprintCase(ctx context.Context, arg UpsertFingerprintCaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertFingerprintCase,
		arg.SourceDataset,
		arg.SourceRow,
		arg.CaseID,
		arg.Description,
		arg.ResponsibleUser,
		arg.ComparisonType,
		arg.RelatedReference,
		arg.RelatedReferenceKind,
	)
	return err
}

const upsertInfoBioEnrollment = `-- name: UpsertInfoBioEnrollment :exec
INSERT INTO infobio_enrollments
    (nif, numero_identificacao, rin, nome, data_nascimento, cpf, nome_pai, nome_mae, container_number, nist_path, storage_ref, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (nif) DO UPDATE SET
    numero_identificacao = EXCLUDED.numero_identificacao,
    rin = EXCLUDED.rin,
    nome = EXCLUDED.nome,
    data_nascimento = EXCLUDED.data_nascimento,
    cpf = EXCLUDED.cpf,
    nome_pai = EXCLUDED.nome_pai,
    nome_mae = EXCLUDED.nome_mae,
    container_number = EXCLUDED.container_number,
    nist_path = EXCLUDED.nist_path,
    storage_ref = EXCLUDED.storage_ref,
    source = EXCLUDED.source,
    confirmed_at = NOW(),
    updated_at = NOW()
`

type UpsertInfoBioEnrollmentParams struct {
	Nif                 string         `db:"nif" json:"nif"`
	NumeroIdentificacao sql.NullString `db:"numero_identificacao" json:"numero_identificacao"`
	Rin                 sql.NullString `db:"rin" json:"rin"`
	Nome                sql.NullString `db:"nome" json:"nome"`
	DataNascimento      sql.NullString `db:"data_nascimento" json:"data_nascimento"`
	Cpf                 sql.NullString `db:"cpf" json:"cpf"`
	NomePai             sql.NullString `db:"nome_pai" json:"nome_pai"`
	NomeMae             sql.NullString `db:"nome_mae" json:"nome_mae"`
	ContainerNumber     sql.NullString `db:"container_number" json:"container_number"`
	NistPath            sql.NullString `db:"nist_path" json:"nist_path"`
	StorageRef          sql.NullString `db:"storage_ref" json:"storage_ref"`
	Source              string         `db:"source" json:"source"`
}

func (q *Queries) UpsertInfoBioEnrollment(ctx context.Context, arg UpsertInfoBioEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertInfoBioEnrollment,
		arg.Nif,
		arg.NumeroIdentificacao,
		arg.Rin,
		arg.Nome,
		arg.DataNascimento,
		arg.Cpf,
		arg.NomePai,
		arg.NomeMae,
		arg.ContainerNumber,
		arg.NistPath,
		arg.StorageRef,
		arg.Source,
	)
	return err
}
