package cases

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/rodfileto/trackid/db"
)

// ValidationError is a case-creation error caused by bad input (missing or
// invalid fields). It is returned by Create so HTTP handlers can map it to a
// 400 without leaking internal errors.
type ValidationError string

func (e ValidationError) Error() string { return string(e) }

// CreateInput is what the API's create-case endpoint needs: the case's type
// (CRIMINAL/CIVIL), its modality and a description. The case_id is generated by
// TrackID, not supplied.
type CreateInput struct {
	CaseType    string
	Modality    string
	Description string
}

// maxNumberingAttempts bounds how many times Create retries when a concurrent
// create raced to the same (year, number). See isDuplicateNumber.
const maxNumberingAttempts = 3

// Create inserts a new biometric case, generating its "<year>.<sequence>"
// case_id (e.g. "2026.0001") from the current year and the next sequential
// number for that year. Numbering is done in Go: the highest case_number for
// the year is read inside a transaction and incremented, and the unique
// (case_year, case_number) index is the only database-level enforcement
// against a duplicate.
func Create(ctx context.Context, sqlDB *sql.DB, input CreateInput) (Case, error) {
	if sqlDB == nil {
		return Case{}, fmt.Errorf("cases: nil db")
	}

	caseType := strings.ToUpper(strings.TrimSpace(input.CaseType))
	if !validCaseType(caseType) {
		return Case{}, ValidationError("case_type must be CRIMINAL or CIVIL")
	}
	modality := strings.ToUpper(strings.TrimSpace(input.Modality))
	if modality != "FACIAL" && modality != "FINGERPRINT" {
		return Case{}, ValidationError("modality must be FACIAL or FINGERPRINT")
	}
	description := strings.TrimSpace(input.Description)
	if description == "" {
		return Case{}, ValidationError("description is required")
	}

	year := time.Now().Year()

	for attempt := 1; ; attempt++ {
		created, err := createNumbered(ctx, sqlDB, year, caseType, modality, description)
		if err == nil {
			return created, nil
		}
		if !isDuplicateNumber(err) || attempt >= maxNumberingAttempts {
			return Case{}, err
		}
	}
}

// createNumbered reads the current max case_number for the year and inserts the
// next one in a single transaction.
func createNumbered(ctx context.Context, sqlDB *sql.DB, year int, caseType, modality, description string) (Case, error) {
	tx, err := sqlDB.BeginTx(ctx, nil)
	if err != nil {
		return Case{}, err
	}
	defer tx.Rollback()

	q := db.New(tx)

	maxNumber, err := q.MaxCaseNumberForYear(ctx, int32(year))
	if err != nil {
		return Case{}, fmt.Errorf("cases: read max case number: %w", err)
	}
	number := maxNumber + 1

	caseID := fmt.Sprintf("%04d.%04d", year, number)

	row, err := q.CreateBiometricCase(ctx, db.CreateBiometricCaseParams{
		CaseID:      caseID,
		CaseType:    caseType,
		Modality:    modality,
		Description: description,
		CaseYear:    sql.NullInt32{Int32: int32(year), Valid: true},
		CaseNumber:  sql.NullInt32{Int32: number, Valid: true},
	})
	if err != nil {
		return Case{}, fmt.Errorf("cases: create biometric case: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return Case{}, err
	}

	return Case{CaseID: row.CaseID, CaseType: row.CaseType, Modality: row.Modality, Description: row.Description}, nil
}

// isDuplicateNumber reports whether err is a unique violation on the
// (case_year, case_number) index — the signature of a concurrent create that
// raced for the same number.
func isDuplicateNumber(err error) bool {
	return err != nil && strings.Contains(err.Error(), "biometric_cases_year_number_key")
}
